-- 코드를 입력하세요
# 식품ID : PRODUCT_ID
# 식품이름 : PRODUCT_NAME
# 생산일자 : PRODUCE_DATE
# 총매출: TOTAL_SALES, DESC, 식품ID ASC

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE*SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P LEFT JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE <= '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC