SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.ADDRESS LIKE "서울%"
AND R.REST_ID = I.REST_ID
GROUP BY R.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;